<?php

namespace Moltaqa\Wasl;

/**
 * Based On Integration Guide for Dispatching Companies
 * Version v2.24
 * Version date 22/05/2023
 */
class RejectionReasons
{
    const ALIEN_LEGAL_STATUS_NOT_VALID = "ALIEN_LEGAL_STATUS_NOT_VALID";
    const MAX_AGE_NOT_SATISFIED = "MAX_AGE_NOT_SATISFIED";
    const MIN_AGE_NOT_SATISFIED = "MIN_AGE_NOT_SATISFIED";
    const DRIVER_IDENTITY_EXPIRED = "DRIVER_IDENTITY_EXPIRED";
    const DRIVER_IS_BANNED = "DRIVER_IS_BANNED";
    const DRIVER_LICENSE_EXPIRED = "DRIVER_LICENSE_EXPIRED";
    const DRIVER_LICENSE_NOT_ALLOWED = "DRIVER_LICENSE_NOT_ALLOWED";
    const VEHICLE_INSURANCE_EXPIRED = "VEHICLE_INSURANCE_EXPIRED";
    const VEHICLE_LICENSE_EXPIRED = "VEHICLE_LICENSE_EXPIRED";
    const VEHICLE_NOT_INSURED = "VEHICLE_NOT_INSURED";
    const OLD_VEHICLE_MODEL = "OLD_VEHICLE_MODEL";
    const PERIODIC_INSPECTION_POLICY_EXPIRED = "PERIODIC_INSPECTION_POLICY_EXPIRED";
    const DRIVER_FAILED_CRIMINAL_RECORD_CHECK = "DRIVER_FAILED_CRIMINAL_RECORD_CHECK";
    const DRIVER_REJECTED_CRIMINAL_RECORD_CHECK = "DRIVER_REJECTED_CRIMINAL_RECORD_CHECK";
    const CRIMINAL_RECORD_CHECK_PERIOD_EXPIRED = "CRIMINAL_RECORD_CHECK_PERIOD_EXPIRED";
    const VEHICLE_PLATE_TYPE_NOT_ALLOWED = "VEHICLE_PLATE_TYPE_NOT_ALLOWED";
    const OPERATION_CARD_EXPIRED = "OPERATION_CARD_EXPIRED";
    const DRIVER_ELIGIBILITY_EXPIRED = "DRIVER_ELIGIBILITY_EXPIRED";
    const DRIVER_VEHICLE_INELIGIBLE = "DRIVER_VEHICLE_INELIGIBLE";
    const VEHICLE_ELIGIBILITY_EXPIRED = "VEHICLE_ELIGIBILITY_EXPIRED";
    const NO_VALID_OPERATION_CARD_FOUND = "NO_VALID_OPERATION_CARD_FOUND";
    const NO_PERIODIC_INSPECTION_POLICY_EXPIRY_DATE = "NO_PERIODIC_INSPECTION_POLICY_EXPIRY_DATE";
    const DRIVER_IS_NOT_REGISTERED_IN_VDS = "DRIVER_IS_NOT_REGISTERED_IN_VDS";
}
